name: Webgoat                                 # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "This is a test step"

  odc-backend:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: chmod +x ./run-depcheck.sh
      - run: ./run-depcheck.sh

      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
           name: Depcheck report
           path: reports/dependency-check-report.csv
